### ISSUE TITLE
Python 3.3 Support

### ISSUE THREAD

**Issue by AbdealiJK** [menpo/cyvlfeat#12]
I was wondering if there was interest in adding python 3.3 support. Py3.3 is still being used by a few projects and it would be nice to support it (Add travis build for 3.3, etc)

**Comment by patricksnape** [comment]
If this is a request it is certainly something I can add. I would suggest you move forwards from Python 3.3 but that is not for me to dictate!

**Comment by AbdealiJK** [comment]
Yes, I'd like to have python3.3 support.
I want to use vlfeat in a project with wikimedia's pywikibot to do some image algorithms in Wikipedia, and due to various reasons pywikibot supports python 2.6 and 3.3. It'd be great if cyvlfeat can also test for these if it's not too much trouble :)
I believe python 2.6 may have some major issues, so I understand if that's not done, but 3.3 support would be awesome.

PS: I attempted to do this myself at https://github.com/AbdealiJK/cyvlfeat/tree/ajk/travis and found the the condaci project doesn't support 3.3 (travis build - https://travis-ci.org/AbdealiJK/cyvlfeat/jobs/130517720)

**Comment by patricksnape** [comment]
Unfortunately conda doesn't support Python 3.3 so this is not possible with this project. I looked at the deprecation warnings for 3.3->3.4 and it seems quite unlikely that the code won't work on Python 3.4 or even Python 3.5. In fact, the pywikibot documentation even says [3.3+](https://doc.wikimedia.org/pywikibot/). So you should be able to just use the Python 3.4 or 3.5 builds!

**Comment by AbdealiJK** [comment]
@patricksnape What do you think about testing it with an older version of conda which does support python3.3 ?

**Comment by patricksnape** [comment]
You are free to do this - condaci now supports 3.3 (or at least doesn't disallow it) - but since Continuum no longer supports Python 3.3 it would be very difficult for me to do. I'd have to rebuild numpy >1.10 and Cython for Python 3.3 in order to test it - which I'm afraid I don't have the bandwidth for.
