### ISSUE TITLE
collaboration

### ISSUE THREAD

**Issue by seanv507** [menpo/cyvlfeat#3]
Hi I am planning to convert more functions to cython from mex... what is the procedure to coordinate development.  I am currently working on the sift ( as opposed to dsift) code. (I have done a basic convert of the mex function, need to work on the m function)

should I 
1. fork, 
2. create a branch for each mex function I work on
3. issue pull request as soon as I start working
4: how do I then notify that I consider the feature ready to pulled into your main branch...

**Comment by jabooth** [comment]
Hi @seanv507,

Thanks for being interested in getting involved, that's great!

The workflow you suggested sounds very sensible. To be concrete and to address your questions, I would:

1. Fork menpo/cyvlfeat
2. Make a new branch for each feature addition
3. Immediately open a PR for each branch to let us know you are working on porting a feature, and so we can track progress.
4. When you feel the code is ready, or if you just want a review on something, ping @patricksnape in the relevant PR and we'll come take a look.

Note that in general @patricksnape manages cyvlfeat development and has final say on PRs etc, but he's away on vacation until the end of the week so I'm (@jabooth) happy to be your point of contact until he gets back.

Let me know if you have any more questions!

**Comment by patricksnape** [comment]
Thanks @jabooth! 

@seanv507 I'm just on holiday at the moment - but totally agree with @jabooth. I am incredibly open to any contribution and all I would do is make sure that the code style is relatively consistent.

To note - current development is based on a build system called ``conda`` and I suggest you use that too. In other words, make the changes/add new Cython files, make sure they are listed in the ``setup.py`` and then build them using ``conda``.

If you need more help, I will make sure to add more information to the README next week.

Thanks a lot and I look forward to working with you!

**Comment by seanv507** [comment]
Great.  I haven't used conda before for building... will have a look. one
request... could cysift be renamed given that its implementing dsift, and I
am working on adding sift.
sean

**Comment by patricksnape** [comment]
I think I had named it cysift because I was coping the Matlab interface, and the sift implementations (dense or sparse) are in the same C file... I think.

In general, try to match the Matlab interface as closely as is sensible without ending up with something that isn't Pythonic. If you need to move files around, that is fine with me.

**Comment by williamkreamer** [comment]
Hi @patricksnape and @jabooth . I'm interested in adding the vl_fisher_encode function to the cyvlfeat package. Any tips (beyond the comments above) for how I should get started?

Thanks!

**Comment by patricksnape** [comment]
Hi @williamkreamer! 

We would love contributions from others! What I normally do is try to copy the Matlab interface as closely as possible whilst still remaining Pythonic. So take a look at the Matlab toolbox code and then try and convert that code into Cython. This will usually mean creating some Cython header files to get hold of different vlfeat classes and then essentially just removing all the Mex fuzz and writing it as Cython.

Take a look at the Sift function and compare it to the vl_sift function in Matlab. Hopefully this will show the similarities and differences between Cython and Mex. If you get stuck, just send me an email at my_github_username@gmail.com (fill in my username obviously).
