### ISSUE TITLE
HOG works on single channel images, but not multi-channel images

### ISSUE THREAD

**Issue by chrisdxie** [menpo/cyvlfeat#32]
Hi,

I have been playing with extracting HOG features with your Cython wrapper of VLFEAT. I've noticed that the HOG wrapper works only when the data is a single-channel image (e.g. grayscale). Thus, it passes the tests (the test image is a single-channel image). For some odd reason, it does not work on RGB or other multi-channel images. 

What I mean when it "works", is that I'm comparing it numerically to running the same function in VLFEAT (0.9.20) in Matlab.

Can someone help me out here? I'm not sure how to fix this so it works on RGB images.

**Comment by stbook** [comment]
I run into the same problem.

**Comment by chrisdxie** [comment]
@stbook follow the pull request from https://github.com/menpo/cyvlfeat/pull/31/commits. The most recent commit (Sep 4, 2016) has code that fixes the issue.

**Comment by stbook** [comment]
Thanks. It works.

**Comment by patricksnape** [comment]
Merged
