### ISSUE TITLE
Problem with the dimension of the Fisher function

### ISSUE THREAD

**Issue by wuyuejinxia** [menpo/cyvlfeat#34]
The parmeters;
means:[F,N],covariances：[F,N]
F is GMM component,N is feature dimensionality
but in the fisher.py file

D = means.shape[0] 
K = means.shape[1]
D is the feature dimensionality
K is the number of GMM component
if coveriances.shape[1] != K ...

In fact, D is mean.shape[1] k = means.shape[0]
and if  coveriances.shape[0] != K ...

**Comment by msminhas93** [comment]
The order in which the gmm function outputs the values is different from that specified in the documentation.
The correct order is means, covars, priors, LL, posteriors. And your function should work.
