### ISSUE TITLE
any plan to merge the current pr?

### ISSUE THREAD

**Issue by hubutui** [menpo/cyvlfeat#48]
Hey, it has been a long time since last release. Is there any plan to add more function binding, say the ones in https://github.com/menpo/cyvlfeat/pulls?

**Comment by patricksnape** [comment]
I currently don't have any bandwidth to work on these things - but if you want to review and test the existing PRs then I am happy to merge them and cut a new release

**Comment by hubutui** [comment]
@patricksnape OK, I have create a pr https://github.com/menpo/cyvlfeat/pull/49. I add some modification to fix the conflicts and update `__init__.py` files.

Another question, https://github.com/menpo/cyvlfeat/blob/master/conda/lena.dat is not installed by `python setup.py install`, but https://github.com/menpo/cyvlfeat/blob/master/cyvlfeat/test_util.py#L1 needs it. Or maybe `test_util.py` should be not installed, but just for testing?

**Comment by patricksnape** [comment]
Yes we should ship a test file with the package. We also shouldn't use Lena really. I'll make an issue to track this

**Comment by patricksnape** [comment]
Release made - thanks for the hard work

https://github.com/menpo/cyvlfeat/releases/tag/v0.6.0

https://github.com/conda-forge/cyvlfeat-feedstock/pull/3
