### ISSUE TITLE
duplicate cyvlfeat/cy_utils.pxd and cyvlfeat/cy_util.pxd?

### ISSUE THREAD

**Issue by hubutui** [menpo/cyvlfeat#53]
Hey, it seems that you add `cyvlfeat/cy_utils.pxd` which only contains a function `inline np.dtype dtype_from_memoryview` in https://github.com/menpo/cyvlfeat/commit/75c24c79db80a4c2dba4836cbe9a1843f4293f68. However, there is one extractly the same in `cyvlfeat/cy_util.pxd`.

**Comment by patricksnape** [comment]
https://github.com/menpo/cyvlfeat/pull/55

**Comment by patricksnape** [comment]
Closed by #55
