### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by justinhan22** [menpo/cyvlfeat#61]
```
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    build_extension_from_pyx('cyvlfeat/fisher/cyfisher.pyx'),
  File "setup.py", line 70, in build_extension_from_pyx
    include_dirs.append(os.environ['LIBRARY_INC'])
  File "C:\Program Files\Python37\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'LIBRARY_INC'
```
when I install set.py (in windows 10, python 3.8), get error like this, how to set the "LIBRARY_INC" path?

**Comment by hsqaihkl** [comment]
@justinhan22 
 Hi，did you solve this problem?I met it too!

**Comment by hsqaihkl** [comment]
@justinhan22 
Hi，I have solve this problem:
You need to add environment variables:
My is "LIBRARY_INC" = "C:\Users\xxx\.conda\pkgs\vlfeat-0.9.20-h2fa13f4_1002\Library\include"

**Comment by patricksnape** [comment]
Yes you should always try and build the package with conda and then the environment variables are set correctly
