### ISSUE TITLE
New release on pypi ?

### ISSUE THREAD

**Issue by dyoussef** [menpo/cyvlfeat#63]
Dear @patricksnape et al., 

I am very interested in this project and I would like to know if you will upload a new release version on pypi with this commit : https://github.com/menpo/cyvlfeat/commit/831fe557a7396a8c7b49fc8074701d848e86a39f in it soon.

Thanks,
David Youssefi

**Comment by patricksnape** [comment]
Ask and you shall receive :)

https://pypi.org/project/cyvlfeat/0.7.0/
